name: Test and Deploy
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v1
        name: Cache Stack
        with:
          path: ~/.stack/
          key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - run: mkdir -p $HOME/.local/bin
      - name: Setup Stack
        run: curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/stack'
      - name: Setup SASS
        run: curl -L https://github.com/sass/dart-sass/releases/download/1.25.0/dart-sass-1.25.0-linux-x64.tar.gz | tar xz --wildcards --strip-components=1 -C $HOME/.local/bin '*/sass' '*/src'

      - name: Build dependencies
        run: $HOME/.local/bin/stack --no-terminal build
      - name: Build website
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          $HOME/.local/bin/stack exec blog-src build

      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          mkdir $HOME/.ssh
          chmod 700 $HOME/.ssh
          echo '${{ secrets.SSH_DEPLOY_KEY }}' > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          rsync -a --delete _site/ ${{ secrets.SSH_DEPLOY_USER }}@${{ secrets.SSH_DEPLOY_HOST }}:~/html/
